### ISSUE TITLE
Calendar component

### ISSUE THREAD

**Issue by positlabs** [orgenic/orgenic-ui#39]
**Is your feature request related to a problem? Please describe.**
Why isn't calendar built in as a native input type?! Also, I haven't seen any date range pickers.

**Describe the solution you'd like**
I want a clean, extensible, responsive web-component calendar. It could be used to select single dates or date ranges. It could also be used to simply display information, but maybe that's getting too far into specific use-cases.

**Describe alternatives you've considered**
There are too many to name!

**Additional context**

<img width="649" alt="Screen Shot 2019-05-07 at 12 28 34 PM" src="https://user-images.githubusercontent.com/1918844/57316381-aaeb6d00-70c3-11e9-83d5-457f0fcb2fbf.png">

<img width="405" alt="Screen Shot 2019-05-07 at 12 27 22 PM" src="https://user-images.githubusercontent.com/1918844/57316321-8394a000-70c3-11e9-9244-d21ad6f6d45e.png">

**Comment by Cr45hCode** [comment]
Hi @positlabs!

First of all, sorry for the late response, but thank you very much for your request :D
You are right, the Datepicker is an important feature that is missing in the current version, but there are good news: it will be part of an upcomming version.
We can not exactly tell when this will be released, but it's on the way - so stay tuned ;)

If there is anything else we can do for you, do not hesitate to contact us.
Thanks again!
