### ISSUE TITLE
Layout-Container Component

### ISSUE THREAD

**Issue by Cr45hCode** [orgenic/orgenic-ui#62]
Design and implement an easy to use LayoutContainer, letting users manage the layout of their site and/or component content.

**Comment by DeeJayTC** [comment]
looks like you added this already? @Cr45hCode

**Comment by Cr45hCode** [comment]
Hi @DeeJayTC,

that's correct. Just forgot to close the issue.
Thanks for the hint ;)

Have a great weekend.
