### ISSUE TITLE
Placeholder text is shown behind date value.

### ISSUE THREAD

**Issue by m4cx** [orgenic/orgenic-ui#69]
**Describe the bug**
The placeholder text is not displayed on top of the entered value but is still shown as placeholder behind the entered value.

**To Reproduce**
1. Select a value through the flyout.
2. Click on the datepicker again to reopen the flyout.
3. Close the flyout by clicking again on the control. NOT THE FLYOUT.
4. See error (like described and shown in the picture)

**Expected behavior**
The placeholder text should be displayed on top of the entered value.

**Screenshots**

![image](https://user-images.githubusercontent.com/363497/59466135-cf5a0800-8e2c-11e9-8667-ee7969f0241a.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 74.0.3729.169

**Comment by Cr45hCode** [comment]
Thank you very much, for reporting this issue.

Closing this, as it will be fixed with the next release ;)
