### ISSUE TITLE
Missing moment package

### ISSUE THREAD

**Issue by andi-d** [orgenic/orgenic-ui#72]
**Describe the bug**
The following error occurs when running an angular app which is using orgenic-ui:

ERROR in node_modules/@orgenic/orgenic-ui/dist/types/components/og-internal-calendar/interfaces/og-calendar-date-decorator.d.ts(1,24): error TS2307: Cannot find module 'moment'.

moving the moment from devDependencies to dependencies in package.json should fix that error.

**To Reproduce**
1. ng new my-angular-app
2. cd my-angular-app
3. npm i @orgenic/orgenic-ui
4. include orgenic-ui in main.ts like stated in the docs
5. ng serve

**Expected behavior**
app should compile

**Screenshots**
![Screenshot_20190622_004342](https://user-images.githubusercontent.com/679873/59955081-6f94da00-9488-11e9-8786-c038adebdbb4.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux

**Comment by Cr45hCode** [comment]
will be fixed with: https://github.com/orgenic/orgenic-ui/pull/118
